/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    ColourSchemeToggle: typeof import('./components/ColourSchemeToggle.vue')['default']
    Console: typeof import('./components/Console.vue')['default']
    FullScreenToggle: typeof import('./components/FullScreenToggle.vue')['default']
    HelpIcon: typeof import('./components/HelpIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SerialApiUnsupportedModal: typeof import('./components/SerialApiUnsupportedModal.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    TerminalThemePicker: typeof import('./components/TerminalThemePicker.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    WelcomeModal: typeof import('./components/WelcomeModal.vue')['default']
    Xterm: typeof import('./components/Xterm.vue')['default']
  }
}
